<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-A11BB6J" failures="0" tests="6" name="sele1.TestngInotationsWithParameters" time="1.041" errors="1" timestamp="2022-06-01T18:04:58 IST" skipped="2">
  <testcase classname="sele1.TestngInotationsWithParameters" name="testc" time="0.003"/>
  <system-out/>
  <testcase classname="sele1.TestngInotationsWithParameters" name="testc" time="0.002"/>
  <system-out/>
  <testcase classname="sele1.TestngInotationsWithParameters" name="testa" time="1.027">
    <error message="Method sele1.TestngInotationsWithParameters.testa() didn&#039;t finish within the time-out 1000" type="org.testng.internal.thread.ThreadTimeoutException">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method sele1.TestngInotationsWithParameters.testa() didn't finish within the time-out 1000
at org.testng.internal.invokers.MethodInvocationHelper.invokeWithTimeoutWithNewExecutor(MethodInvocationHelper.java:375)
at org.testng.internal.invokers.MethodInvocationHelper.invokeWithTimeout(MethodInvocationHelper.java:296)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:679)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- testa -->
  <system-out/>
  <testcase classname="sele1.TestngInotationsWithParameters" name="testd" time="0.007">
    <skipped/>
  </testcase> <!-- testd -->
  <system-out/>
  <testcase classname="sele1.TestngInotationsWithParameters" name="testb" time="0.002"/>
  <system-out/>
  <testcase classname="sele1.TestngInotationsWithParameters" name="teste">
    <skipped/>
  </testcase> <!-- teste -->
  <system-out/>
</testsuite> <!-- sele1.TestngInotationsWithParameters -->
